### ISSUE TITLE
The notify() function in a WSL environment

### ISSUE THREAD

**Issue by mark-alexandre** [jolicode/JoliNotif#102]
Hello,

I'm in a WSL2 environment under Windows 11 in order to launch my Castor commands and with the Castor.PHAR archive for Windows (since it's this one to take even for WSL). I just tried your notification function but it doesn't trigger any notification.

I have checked my notifications options btw, and everything is properly configured. I wonder the reason behind this : is this a WSL related issue which can't communicate properly with Windows ?

```php
#[AsTask(description: 'Suppression des volumes, conteneurs et réseaux créés pour le projet')]
function clean(bool $force = false)
{
    notify('The infrastructure has been destroyed.');
}
```

**Comment by lyrixx** [comment]
For the record, I have move the issue from castor to jolinotif.

**Comment by mark-alexandre** [comment]
> When using Windows phar/binary: Nothing appear (no throw, no notification on Windows)

I have exactly the same behavior.
