### ISSUE TITLE
Requirement of psr/log 3.0

### ISSUE THREAD

**Issue by reinfi** [jolicode/JoliNotif#108]
Hey,

do your code really depends on `"psr/log": "^3.0"`? Or would 1.0 and 2.0 also be valid?

Reason:

This blocks your update in a lot of applications because many library packages from frameworks still does not support latest psr/log. 

If all psr/log versions would be acceptable I'll be happy to submit a pull request.

Best regards
Martin

**Comment by pyrech** [comment]
Hi,

Indeed, we could lower the requirement if it helps new version adoption :+1: I would happily accept such a PR :pray: 

Thanks

**Comment by pyrech** [comment]
v2.7.2 was released with your changes. Thanks @reinfi
