### ISSUE TITLE
Nothing Happen

### ISSUE THREAD

**Issue by cevarief** [jolicode/JoliNotif#11]
I tried php example/index.php, mac osx yosemite, but no notification pop up.

**Comment by pyrech** [comment]
Thanks for reporting the issue.

I just released v1.0.3 to ease the debugging of the example script. Could you please update your version of JoliNotif to 1.0.3, run `php example/index.php` and copy/paste the output of the script. It will help to determine what is the problem (either no notifier is supported or the selected notifier has a problem with the underlying executable).

**Comment by pyrech** [comment]
Hi. Did you try with the latest version to understand what is the nature of the bug? The master branch contains a commit (not yet released) that might even fix it as there was a problem with the OSX version detection.

**Comment by pyrech** [comment]
Closing this issue as no answer for more than 2 weeks. Feel free to reopen it if you're still experiencing problems.
