### ISSUE TITLE
Make the `send()` method always throws in case of failure

### ISSUE THREAD

**Issue by ahmedghanem00** [jolicode/JoliNotif#110]
Hi there,

As stated in the title, wouldn't it be better to make this method always throw an exception in case of any type of failure (e.g., bad exit code, no loaded/valid driver, etc.) instead of the current behavior of returning the generic `false`?

This would also eliminate the need to check the return type of the method to see if it succeeded or not, as an appropriate exception with a clear message would be thrown always, in case anything except success occurred.

**Comment by pyrech** [comment]
In most use cases, I consider notifications as a must have, and not something that should break my code in case something goes wrong (for example for someone using your project on an system where no notifier is available and/or they don't care about notifications).

That being said, we could maybe propose a ThrowableNotifier (any better name?) implementation throwing exceptions for everything wrong. What do you think?

**Comment by ahmedghanem00** [comment]
> we could maybe propose a ThrowableNotifier (any better name?) implementation throwing exceptions for everything wrong. What do you think?

Sounds good, or maybe we go simpler and make it within the DefaultNotifier but in an optional manner? Something like `->shouldAlwaysThrowOnError(bool $status)` ? or in the __constructor?

**Comment by lyrixx** [comment]
I don't really like this kind of flags.
I would go with another methods `sendOrFail()` for examples

**Comment by ahmedghanem00** [comment]
Whatever, It will achieve the same result anyway 😃

**Comment by lyrixx** [comment]
Would you mind working on a PR?

**Comment by ahmedghanem00** [comment]
I'll try to make a one soon

**Comment by lyrixx** [comment]
/
