### ISSUE TITLE
Not working if script run from cron

### ISSUE THREAD

**Issue by neTpyceB** [jolicode/JoliNotif#13]
Ubuntu 14..04
Trying to run file with notifier directly - works.
Trying to run in cron, like:
* * * * * php /path/notifier.php
Nothing happens.

root or my own user - not working
log says script is run ok

Can I run it from cron to get result?

**Comment by damienalexandre** [comment]
Can you try with this?

    * * * * env DISPLAY=:0 php /path/notifier.php Nothing happens.

You may also need to run `xhost +local:`, cf https://help.ubuntu.com/community/CronHowto#GUI_Applications

**Comment by pyrech** [comment]
I'm closing the issue as I added some documentation (based on @damienalexandre's comment) in #16 about usage in cron. Thanks for reporting this issue.

**Comment by neTpyceB** [comment]
Thanks. It works with env... as you said ))

**Comment by rlacerda83** [comment]
I follow these steps, but my notification does not work by cron. Calling the script by teminal or the browser runs normally. Any idea?

**Comment by pyrech** [comment]
@rlacerda83 Did you have a look at the documentation [here](https://github.com/jolicode/JoliNotif/blob/master/doc/04-advanced-usage.md)? Depending on your system, you may also need to use `xhost` (see the attached link https://help.ubuntu.com/community/CronHowto#GUI_Applications)

**Comment by rlacerda83** [comment]
@pyrech , yes, i did!
I run in terminal xhost + to disable it.... but does not work.

I did not perform the xhost + inside the PHP script, but I think it will not make a difference.
My cron: * * * * * env DISPLAY =:0 php /mypath

Ah, im using ubuntu 14.04.
