### ISSUE TITLE
utf-8 not working in windows 7

### ISSUE THREAD

**Issue by johnnymn** [jolicode/JoliNotif#15]
When I try to write utf-8 characters the notification shows me weird characters.

**Comment by pyrech** [comment]
Probably an issue with Notifu, the underlying binary used for Windows 7. I will try to investigate when I get some time.

I should also check other notifiers to see how they behave with Unicode ;)

**Comment by damienalexandre** [comment]
@johnnymn Could you post a code snippet to reproduce? thx!

**Comment by johnnymn** [comment]
This is the script: https://gist.github.com/johnnymn/054dbf8710612d5dda11

I was unable to reproduce the bug on an Ubuntu 14.04 machine.

**Comment by pyrech** [comment]
FYI I can confirm Windows notifiers have some problems with utf-8. I'm still trying to make them working fine with unicode but no luck until now.

**Comment by lyrixx** [comment]
Windows 7 is EOL for 2 years now. That's why I gonna close this issue.

Anyway, thanks for bringing that to the table.
