### ISSUE TITLE
Test and support for Windows 10

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/JoliNotif#17]
Windows 10 ship a new notifier, add support for it!

**Comment by pyrech** [comment]
I'm glad to see that Windows 10 notifications work out of the box :)

![capture-jolinotif-win-10](https://cloud.githubusercontent.com/assets/2021641/9698941/08218a7a-53ce-11e5-8771-90cf08fd3b21.png)

On my computer, the notification doesn't appear on the screen but only in the notification center (maybe a matter of configuration of Windows)
