### ISSUE TITLE
problem with Monolog integration

### ISSUE THREAD

**Issue by kamilsk** [jolicode/JoliNotif#24]
Hi! I found a mistake when writing handler for Monolog based on your useful library:

```php
use Joli\JoliNotif\Notification;
use Joli\JoliNotif\NotifierFactory;

($notifier = NotifierFactory::create()) && $notifier->send(
    (new Notification())
        ->setTitle('Something happen')
        // problem body:
        // ->setBody('[2016-03-15 14:17:21] test.INFO: test [] {"time_execution":"0.000"}')
        // it's ok
        ->setBody('[2016-03-15 14:17:21] test.INFO: test [] {time_execution:0.000}')
);
```

Problem located here: https://github.com/jolicode/JoliNotif/blob/v1.0.4/src/Notifier/AppleScriptNotifier.php#L56

Possible solution:

```php
$script = 'display notification "'. addslashes($notification->getBody()) .'"';
```

What do you think? Can I fix it?

**Comment by pyrech** [comment]
Hi :)

I think `Symfony\Component\Process\ProcessUtils::escapeArgument()` would be better to escape properly the body but not sure it will fix the problem. Could give you give it a try and open a PR? Thanks :wink:

**Comment by kamilsk** [comment]
I tested, works fine.

> Could give you give it a try and open a PR?

Yeah, one moment
