### ISSUE TITLE
Create a script to be called directly on CLI

### ISSUE THREAD

**Issue by pyrech** [jolicode/JoliNotif#29]
This would allow to use JoliNotif from the CLI, without any PHP code needed. This would allow to run something like:

``` shell
jolinotif --title="Hello World" --body="This is a notification"
```

Any opinion about it?

**Comment by damienalexandre** [comment]
Could even be auto-installed by composer. 

:+1:

**Comment by pyrech** [comment]
Done in #42 \o/
