### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by m1guelpf** [jolicode/JoliNotif#31]
I just tried it with the example code and it is showing the Notification successfully sent with Joli\JoliNotif\Notifier\NotifySendNotifier but not working.

**Comment by pyrech** [comment]
Hi, sorry you experienced any error. In order to help you, could you provide some details:
* What is your OS?
* How do you run JoliNotif? Any code example to share?
* Is there any relevant error or log that could provide some details?

Thank you

**Comment by m1guelpf** [comment]
OS: Ubuntu
Code: Cloned repo not working, composer install and sample in repo desc. also not working

**Comment by damienalexandre** [comment]
What code do you try to run and how do you run it?

We can't help you without more informations as the project is working fine here 👍
