### ISSUE TITLE
icon can`t show in mac os 10.12.3

### ISSUE THREAD

**Issue by visonforcoding** [jolicode/JoliNotif#32]
my mac book pro os is macOS 10.12.3 。 the notification can show ,but the icon can`t display.
I am sure the img is exist and the path is right

**Comment by pyrech** [comment]
You probably do not have terminal-notifier nor growl-notify installed on your system. Thus you might be using apple script - which does not allow to use custom icon for notifications.

Could you confirm which tool JoliNotif uses on your system by running the script provided in the example directory? Thanks

**Comment by visonforcoding** [comment]
i can`t . would you tell me how to check which tool  my system use.

**Comment by visonforcoding** [comment]
yes , you are right , i install  terminal-notifier

```shell
brew install terminal-notifier
```
now , the icon can display..  thank you .thank your projcet .it`s very funny

**Comment by pyrech** [comment]
Thanks! :wink:
