### ISSUE TITLE
toast text on Windows 10

### ISSUE THREAD

**Issue by decadence** [jolicode/JoliNotif#41]
Hello.
I see "toast" text on bottom of the popup on Windows 10 with very basic code:

```php
// Create a Notifier
        $notifier = NotifierFactory::create();

        // Create your notification
        $notification =
            (new Notification())
                ->setTitle('Title')
                ->setBody('Done')
                ->setIcon(base_path('chrome.png'))
                ->addOption('subtitle', 'This is a subtitle')// Only works on macOS (AppleScriptNotifier)
                ->addOption('sound', 'Frog') // Only works on macOS (AppleScriptNotifier)
        ;

        // Send it
        $notifier->send($notification);
```

![image](https://user-images.githubusercontent.com/1434668/29274676-4b7f78aa-8111-11e7-80db-e4123e19ac51.png)

**Comment by pyrech** [comment]
I guess this is due to Toaster, the underlying notifier used on Windows 10. Not sure if we can hide this text. I will maybe try it when I get a Windows 10 computer :wink:

**Comment by decadence** [comment]
Thanks. Not a big deal but would be nice to hide it :)

**Comment by pyrech** [comment]
After looking at the code of Toaster (and from what I can understand of C#), there is no option provided to hide this text. Closing the issue for now. If someone find a clue to hide this text, do not hesitate to reopen the issue 👍 . Thanks

**Comment by decadence** [comment]
Strange... but thanks for investigating.
