### ISSUE TITLE
Synology DSM 6.1 Not working

### ISSUE THREAD

**Issue by fpardigon** [jolicode/JoliNotif#44]
> Synology DS416+
> Php : 5.6
> Apache : 2.6
> ALL module php active

> message:
> No supported notifier

I copied the directory on a mac with a MAMP, everything works, but impossible to run on synology, an idea?

merci

**Comment by pyrech** [comment]
Hi, currently JoliNotif supports only notification through local provider (with implementations for some notifier available on MacOS, Linux and Windows). Is there an executable that JoliNotif could use on Synology? How and where would the notification be displayed?

**Comment by fpardigon** [comment]
Hi, we use the web server on synology to process photos via an API, we would like the notification to appear on the desktop of local users via the chrome browser, Synology is on  GNU / Linux kernel

**Comment by pyrech** [comment]
JoliNotif is a lightweight PHP library that run binaries through CLI and as such, it cannot send notifications to your browser. JoliNotif has been designed from the start to be used on CLI and does not currently support any kind of remote notification.

**Comment by fpardigon** [comment]
thank you for the clarification
