### ISSUE TITLE
Add support for Linux subsystem on Windows

### ISSUE THREAD

**Issue by manticorp** [jolicode/JoliNotif#48]
This may be a complete edge case, but I needed desktop notifications on the linux subsystem running on windows.

The good news is that the ```ToastNotifier``` works fine, but detecting this situation is a little complex it would seem and there are no definitive answers out there.

I couldn't find any information on how to detect the linux subsystem running on windows, but the best thing I could find was:

```php
 $isLinuxOnWindows = mb_strpos(strtolower(php_uname()), 'microsoft') !== false
```

I have implemented this in my setup by extending the NotifierFactory, and rewriting the methods:

```php
class NotifierFactory extends JoliNotifFactory
{
    /**
     * @return Notifier[]
     */
    public static function getDefaultNotifiers()
    {
        // Don't retrieve notifiers which are certainly not supported on this
        // system. This helps to lower the number of process to run.
        if (OsHelper::isUnix() && !mb_strpos(strtolower(php_uname()), 'microsoft')) {
            return self::getUnixNotifiers();
        }

        return self::getWindowsNotifiers();
    }

    /**
     * @return Notifier[]
     */
    private static function getWindowsNotifiers()
    {
        return [
            new ToasterBashWindowsNotifier(),
            new ToasterNotifier(),
            new NotifuNotifier(),
        ];
    }
}
```

And then creating a ```ToasterBashWindowsNotifier``` that just extends ```ToasterNotifier```:

```php
class ToasterBashWindowsNotifier extends ToasterNotifier
{
    /**
     * {@inheritdoc}
     */
    public function canBeUsed()
    {
        return OsHelper::isUnix() && mb_strpos(strtolower(php_uname()), 'microsoft');
    }
}
```

and all works now as expected, with notifications popping up as normal.

The only thing I've found is that icons seem to break it at the moment.

I haven't looked in detail, but my guess would be that:

* Notifier expects a path it can resolve in the current OS, so passing a windows style path means the icon doesn't even try to get displayed when running in Linux (it can't find the file). So e.g. passing ```C:\myapp\myicon.png``` doesn't work.
* Toast expects a path it can resolve in Windows, and passing a Linux path causes it to fail - so passing ```mnt/c/myapp/myicon.png``` doesn't work.

I've tracked this down to the 'setIcon' function on the notification, where it does a 'realpath' which turns to null if a windows path is given on the linux subsystem - fuuuuuu.

Icons aren't 100% important to me, so I can forgo supporting them atm.

I did have a thought that Toast might be able to support some sort of base64 encoded png - but I can't get it to work.

**Comment by pyrech** [comment]
Hello :)

Interesting use case! Thanks for sharing your search on the topic. I'm not yet sure this should be part of JoliNotif. Anyway to make icons work maybe you can extend the Notification class to override the icon setter to set an icon path not "realpathed"?

**Comment by manticorp** [comment]
@pyrech 

Yes - this is more included for brevity, in case it helps someone else out there :) Fortunately it is easy enough to just extend those two classes.

R.e. the icon - could do, that does work - but if an invalid path is passed the notification bugs out, displaying default text, so I ideally need some way of verifying it's a valid path inside the application, but pass a windows path to the notification.

My application is running on a few systems, with potentially different paths to the app icon, so I need a dynamic solution rather than a hard coded one.

Perhaps unsurprisingly there is very little information on the topic ;)

**Comment by angusbitbucket** [comment]
First of all, thank you very much for reading my email.
I am very interested in your Add support for Linux subsystem on Windows can send source code to me?
thank you

**Comment by angusbitbucket** [comment]
I encountered the same problem and I need an demo，help me

**Comment by manticorp** [comment]
@angusbitbucket 

My top comment provides a demo.

Simply use the ```NotifierFactory``` implementation above instead of the ```Joli\JoliNotif\NotifierFactory``` class, making sure you also have the ```ToasterBashWindowsNotifier ``` available.

It will 'detect' bash running on windows.

See:

https://github.com/jolicode/JoliNotif/blob/master/src/NotifierFactory.php

and

https://github.com/jolicode/JoliNotif/blob/master/src/Notifier/ToasterNotifier.php

**Comment by angusbitbucket** [comment]
Thank you very much again

2018-03-26 2:56 GMT+08:00 Harry Mustoe-Playfair <notifications@github.com>:

**Comment by pyrech** [comment]
I'm not promising anything, but I will try to see how this can be supported in JoliNotif in the coming days :wink:

**Comment by pyrech** [comment]
@manticorp I just pushed a WIP branch to add support for Windows Subsystem for Linux (WSL) : https://github.com/jolicode/JoliNotif/tree/feature/windows-subsystem-linux

I didn't test it on a real Windows for now and I plan to it soon.
But you are more than welcome if you want to give it a try before I do :smile: (notification may work too)

**Comment by AdamHebby** [comment]
Please note on the branch above, it is behind master and I had errors:
```PHP Warning:  require(blah/vendor/jolicode/jolinotif/vendor/autoload.php): failed to open stream: No such file or directory in blah/vendor/jolicode/jolinotif/jolinotif on line 7
PHP Fatal error:  require(): Failed opening required 'blah/vendor/jolicode/jolinotif/vendor/autoload.php' (include_path='.:/usr/share/php') in blah/vendor/jolicode/jolinotif/jolinotif on line 7```

I fixed these by cloning this repo, checking out into `feature/windows-subsystem-linux` and pulling in master, then overwriting my composer required folder with the now up to date repo.

@pyrech Please can you pull in master on your branch and push back up?

BTW - Thank you very much! This fix is just what I was looking for

**Comment by pyrech** [comment]
I just rebased the branch on top of master :wink:
Please test it and confirm everything works :+1:
Thanks

**Comment by AdamHebby** [comment]
Awesome, that works. Thanks for updating.

May I also suggest that you change line 84 in `src/Notification.php` to the following:
```
$icon = OsHelper::isWindowsSubsystemForLinux()
    ? preg_replace('/^\/mnt\/([a-z])\//', '$1:\\', $icon, 1)
    : realpath($icon);
```

If you use a relative file url (eg `__DIR__ . '/logo.png'`) for an icon, it gets converted to `/mnt/$/...blah/logo.png` if it's on a mounted drive and Toast doesn't seem to like that. Also as a user pointed out earlier, the whole notification breaks when the icon fails to load so this isn't great.

This fixes it for me by converting it to a real Windows path (eg `C:\...`).

**Comment by pyrech** [comment]
Hi, I finally took the time to update the branch and opened a PR (#55). I also added the change you suggested on Notification path :wink: 

Please test the branch one more time and I will be able to merge the PR and release it ASAP. Thanks.
