### ISSUE TITLE
Support to Symfony Process ~4.0

### ISSUE THREAD

**Issue by nunomaduro** [jolicode/JoliNotif#49]
Thanks for this package.

Any plans for adding support to symfony/process ~4.0?

**Comment by pyrech** [comment]
Oups, I thought support for SF4 was already in place. I will add it and release it today.

Thanks for your reminder :+1:

**Comment by pyrech** [comment]
FYI, support for Symfony 4 is available in the 2.0 release

**Comment by nunomaduro** [comment]
Thanks for being so quick! 🎉
