### ISSUE TITLE
Usage of return hint `self` makes inheritance impossible

### ISSUE THREAD

**Issue by nunomaduro** [jolicode/JoliNotif#51]
On the release `v2.0.0` the feature `Added typehints everywhere` was introduced. I am having an problem extending classes that makes usage of the return hint `self`. Example:

```php
class MyClass extends \Joli\JoliNotif\Notification
{
...

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }
}
```

The following `Fatal error` is throw: `Declaration of Joli\JoliNotif\Notification::setTitle(string $title): Joli\JoliNotif\Notification must be compatible with MyClass.`.

Solution 1: Remove those return hints.

Solution 2: Create a interface and use it on the return hint `public function setTitle(string $title): NotificationInterface`.

What are your thoughts on this?

**Comment by pyrech** [comment]
Solution 3: use the Notification class as the return typehint of your overidden method. I may miss something but I don't see any problem when doing this :wink:

Anyway, the Notification class was not really created to be extendable. Just to better understand your situation, why do you need to extend this class?

**Comment by nunomaduro** [comment]
You are right. The solution `use the Notification class as the return typehint of your overidden method` work like a charm.

Thanks for the quick response! 👏
