### ISSUE TITLE
Trigger the notification from a webapp

### ISSUE THREAD

**Issue by mwakaambrose** [jolicode/JoliNotif#53]
Greate project you got here, I was wondering if its posible to trigger this notifications from a webapp. I tried but the notification doesn't show. If I run the example from the terninal then it shows. Any pointers will be greatly appreciated.
From web
![screen shot 2018-06-09 at 21 19 04](https://user-images.githubusercontent.com/8328295/41194859-0db75b90-6c2b-11e8-88a6-93e1a8fd16d5.png)
From terminal
![screen shot 2018-06-09 at 21 19 25](https://user-images.githubusercontent.com/8328295/41194890-9c311672-6c2b-11e8-94c1-9f0bdf931d57.png)
![screen shot 2018-06-09 at 21 19 47](https://user-images.githubusercontent.com/8328295/41194898-d09f2b88-6c2b-11e8-9ac0-238d3188bea6.png)

**Comment by darkterminal** [comment]
Have you ever used **ReactPHP**? use _EventLoop_ to create your own costume server that lets you create notifications from webapp. CMIW

**Comment by darkterminal** [comment]
@mwakaambrose this my sample:

![jolinotifwebappnotification](https://user-images.githubusercontent.com/32319439/41196645-731e2ae2-6c6f-11e8-9d1f-3b247fa5eb1a.png)

if you wish, you can give me an email and i will send it!

Regard,

**Comment by mwakaambrose** [comment]
@darkterminal No, I haven't looked into that but sounds great. Am looking at their documentation right now. You could send me that sample at amsxbyte@gmail.com.  Thanx

**Comment by darkterminal** [comment]
@mwakaambrose i just sent email for you. Have NIce Day!

**Comment by mwakaambrose** [comment]
Thanks @darkterminal am closing this issue.
