### ISSUE TITLE
Notification permission

### ISSUE THREAD

**Issue by tahseen2k8** [jolicode/JoliNotif#56]
Is there any way to ask for permission and if user allow only then 
we can show notification . right now it is showing all notification by default

**Comment by pyrech** [comment]
I'm not sure to understand what you mean by "Ask for permission".

If you want to conditionnally trigger some notification, you should probably code this logic yourself. In a nutshell, JoliNotif is just a wrapper for the notifier(s) available on your OS, so it's internal logic is quite minimal.

If that can help to clarify your problem, could you paste some pseudo-code of what you would like to achieve? Thanks.

**Comment by tahseen2k8** [comment]
so i am using ubuntu 18.04.1 . xampp is intalled on my system chekout codebase and put index.php on root paste basic trigger of notification mentioned in readme.md. it is not showing me any notification at all 
by debugging i have found this command generated by code . `exec 'notify-send' 'Notification title' 'This is the body of your notification'`. if i execute this command in terminal it is showing me notification properly .but when i  am using it from php code not showing me any notification . most probably some permission issue or i am missing any config .?

**Comment by pyrech** [comment]
Just as a reminder, this library can only send notification to the OS. It can not send any notification when used in web context (FPM). You must run the php script on your terminal. Is it the case?

**Comment by pyrech** [comment]
No news for some months. I will close the issue for now but feel free to reopen when you have more insights on your problem. Thanks.
