### ISSUE TITLE
can't get it to work on OSX Mojave

### ISSUE THREAD

**Issue by vesper8** [jolicode/JoliNotif#57]
Hi there, just started using https://github.com/spatie/phpunit-watcher which uses this package for the desktop notifications.

I noticed that the notifications are not showing up but can't figure out why.

I am using iTerm by the way on OSX Mojave

I installed jolicode/JoliNotif separately to try to debug the issue

Running ```jolinotif --title "Hello" --body "World"```

Does not produce any errors but also no notifications either.

I then tried running the examples/index.php script as suggested in another issue to debug the the problem and the output is simply:
```
Notification failed with Joli\JoliNotif\Notifier\TerminalNotifierNotifier
```

Any idea what's going on? Would love to get this working

**Comment by vesper8** [comment]
Reading https://jolicode.com/blog/desktop-notification-in-php led me to try terminal-notifier manually which led to an error

After reinstalling it with ```brew install terminal-notifier```

and then having to run
```
sudo rm '/usr/local/bin/terminal-notifier'
brew link --overwrite terminal-notifier
```

Now it's working :)

No idea why I had to do all that.. this is an old installation that I've been updating since Yosemite

**Comment by pyrech** [comment]
Nice to see that your problem was solved just by reinstalling terminal-notifier!
Thanks for using JoliNotif.
