### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by szepeviktor** [jolicode/JoliNotif#58]
Is it hard to add a Slack notifier?

**Comment by pyrech** [comment]
Hi,

This library is really oriented for desktop notification and there is no will to implement remote notification at the moment.

But triggerring a Slack notification requires only a few lines of code (sending a HTTP POST to Slack API with a JSON array describing the message). You probably don't need any class from JoliNotif to do it so I can only advice you to implement it directly un jour own project :wink:

**Comment by szepeviktor** [comment]
Thank you.

I thought about a project already using JoliNotif.

**Comment by pyrech** [comment]
The Notifier interface is mainly used inside the NotifierFactory to find the best desktop notifier according to your OS, so these contracts will not help you at all to trigger a Slack notif.

Maybe you can use the Notification class (beware of the icon setter that make some assumption about the local filesystem).

Honestly, I really don't think you will gain anything by tighting the Slack notification to JoliNotif :confused:
