### ISSUE TITLE
Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2

### ISSUE THREAD

**Issue by gboubaker** [jolicode/JoliNotif#59]
Hello and many thanks for this awesome package,

I'm getting a deprecation warning when testing with phpunit:
> Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell.

I solved this problem by changing a line code in Joli\JoliNotif\Util\OsHelper::getMacOSVersion()
from `$process = $process = new Process('sw_vers -productVersion');`
to `$process = new Process(['sw_vers', '-productVersion']);`

**Comment by lyrixx** [comment]
Good catch. Would you mind to submit a PR?
