### ISSUE TITLE
Update symfony/process dependency

### ISSUE THREAD

**Issue by thiagolcks** [jolicode/JoliNotif#64]
Is it possible to update to also work with symfony/process v5?

I'm having a dependency issue with other projects that depend on JoliNotif, but have installed symfony/process v5.

**Comment by lyrixx** [comment]
Sure ! Would you mind submitting a PR ? :pray: Thanks

**Comment by lyrixx** [comment]
Oh, wait, there is already a PR for that: https://github.com/jolicode/JoliNotif/pull/63

**Comment by pyrech** [comment]
I just merged it. I will release it soon :wink:

**Comment by thiagolcks** [comment]
Amazing! Thanks

**Comment by pyrech** [comment]
The support of Symfony 5 has been released in v2.1.0. Enjoy :slightly_smiling_face:
