### ISSUE TITLE
Not working Windows 10

### ISSUE THREAD

**Issue by eleimt** [jolicode/JoliNotif#70]
Not working on Windows 10. Why?

**Comment by pyrech** [comment]
Hi @eleimt
Could you run the embedded example (`php vendor/jolicode/jolinotif/example/index.php`) and report the output? It will help to determine if the problem comes from JoliNotif or from Toaster - the underlying library used on Windows 10

**Comment by eleimt** [comment]
@pyrech 
Yes, sure. My file:
```
<?php

use Joli\JoliNotif\Notification;
use Joli\JoliNotif\Notifier\NullNotifier;
use Joli\JoliNotif\NotifierFactory;

require __DIR__.'/vendor/autoload.php';

$notifier = NotifierFactory::create();

if (!($notifier instanceof NullNotifier)) {
    $notification =
        (new Notification())
            ->setTitle('Notification example')
            ->setBody('This is a notification example. Pretty cool isn\'t it?')
            ->setIcon(__DIR__.'/vendor/jolicode/jolinotif/example/icon-success.png')
    ;

    $result = $notifier->send($notification);

    echo 'Notification ', $result ? 'successfully sent' : 'failed', ' with ', get_class($notifier), PHP_EOL;
} else {
    echo 'No supported notifier', PHP_EOL;
}
```
Result:
`Notification successfully sent with Joli\JoliNotif\Notifier\ToasterNotifier`, but nothing not show. I think problem is Windows 10, but I dont not how to solve it.

**Comment by eleimt** [comment]
@pyrech

**Comment by pyrech** [comment]
I will need to test it on a windows 10 computer when I can (my daily laptop is on Linux)

**Comment by eleimt** [comment]
Okay, thanks.

**Comment by eleimt** [comment]
@pyrech 
I think the problem is on my side.  There are some mistakes with toast.

**Comment by eleimt** [comment]
@pyrech 
This is working https://github.com/mikaelbr/node-notifier, bat jolicode/JoliNoti not :(

**Comment by pyrech** [comment]
Yes, I reproduced the error on my Windows 10. I tried a few things but didn't find a solution yet. I will keep you informed here if I find something 😉

**Comment by eleimt** [comment]
@pyrech 
Okay, thanks 👍

**Comment by pyrech** [comment]
@eleimt Finally found a workaround to fix this issue in #76. I plan to release it as 2.3.0 soon :wink:

**Comment by eleimt** [comment]
@pyrech 
Coole, very much. Thanks. Wait.. 🙂

**Comment by eleimt** [comment]
@pyrech 
It's worked, beautiful. Theanks.
