### ISSUE TITLE
Can't get notifications to work in cron

### ISSUE THREAD

**Issue by BenMorel** [jolicode/JoliNotif#71]
Hi, I've read the [docs on cron](https://github.com/jolicode/JoliNotif/blob/master/doc/04-advanced-usage.md), as well as #13.

I've performed all the suggested steps but can't get the notifications working from cron:

    * * * * * env DISPLAY=:0 php /home/benjamin/script.php

I verified that the cronjob runs fine. I verified my `$DISPLAY`:

    $ echo $DISPLAY
    :0

I've run the suggested `xhost` command as well:

    xhost +local:

But same, no notifications. I'm using Zorin OS 15.3, based on Ubuntu 18.04.

Any idea how to make notifications work in cron?

**Comment by pyrech** [comment]
I can confirm the issue on Ubuntu 20.04 too. I don't know yet how to mitigate this issue but I will update here if we find a solution.

**Comment by pyrech** [comment]
After a few searches I found that using XDG_RUNTIME_DIR env var was enough to make notifications working in cron:

```
* * * * * XDG_RUNTIME_DIR=/run/user/$(id -u) php /path/to/your/script
```

Could you try this new configuration and report there if it worked for you?

**Comment by BenMorel** [comment]
Works perfectly fine for me, merci ! 🎉

Time to update the docs I guess. May I also suggest to rename the [advanced usage](https://github.com/jolicode/JoliNotif/blob/master/doc/04-advanced-usage.md) section of the manual to just "Notifications in cron"? I was expecting to see the cron keyword straight on the homepage, and had to go through each link to find the relevant information.

**Comment by pyrech** [comment]
You're right! I will apply your suggestion in #72 👍 

Thanks!
