### ISSUE TITLE
Icon not shown in desktop notifier

### ISSUE THREAD

**Issue by Echecivuole** [jolicode/JoliNotif#73]
Hi, the desktop notifier works fine, but even adding the code
resource_path('image.png')
the image is not showing. I read some other posts for which it would need required to install other package into the OSX o Windows pc, but this cannot be asked to all users using this feature.

Any solution?

**Comment by lyrixx** [comment]
may be you can use an emoji

**Comment by Echecivuole** [comment]
An emoji!? No the solution would be to allow showing image from path

**Comment by pyrech** [comment]
Hello @Echecivuole,

JoliNotif is PHP library that acts as thin wrapper around the desktop notifiers available on your OS. Here is the list of the supported notifiers: https://github.com/jolicode/JoliNotif/blob/master/doc/03-notifier.md#supported-notifiers

If yours users do not have a supported notifier accepting icons installed on their OS, then I guess there is nothing we can do on our side.

I'm closing the issue as everything is already explained in the documentation but feel free to reopen if you think about a possible workaround.

**Comment by Echecivuole** [comment]
> Hello @Echecivuole,
> 
> JoliNotif is PHP library that acts as thin wrapper around the desktop notifiers available on your OS. Here is the list of the supported notifiers: https://github.com/jolicode/JoliNotif/blob/master/doc/03-notifier.md#supported-notifiers
> 
> If yours users do not have a supported notifier accepting icons installed on their OS, then I guess there is nothing we can do on our side.
> 
> I'm closing the issue as everything is already explained in the documentation but feel free to reopen if you think about a possible workaround.

Hello, thanks for explanation. I need to re-open, but I don't find the way, as I think issue is not related to my OSX system, which currently gets already desktop notifications, but the limit of this package to show in the desktop also an image. Any way to show also the image?

**Comment by damienalexandre** [comment]
As far as we know, there is no solution. Your users need an icon compatible notifier and then JoliNotif will work as you expect. JoliNotif cannot add functionality on top of Operating System notifications.

By the way you never told what system exactly is concerned by your issue. Can you follow those instructions? https://github.com/jolicode/JoliNotif/issues/70#issuecomment-772526821 and report back here.

**Comment by Echecivuole** [comment]
> As far as we know, there is no solution. Your users need an icon compatible notifier and then JoliNotif will work as you expect. JoliNotif cannot add functionality on top of Operating System notifications.
> 
> By the way you never told what system exactly is concerned by your issue. Can you follow those instructions? [#70 (comment)](https://github.com/jolicode/JoliNotif/issues/70#issuecomment-772526821) and report back here.

The issue is concerned to ALL OSX for sure, and probably also to Windows OS, which didn't apply specific programmic actions, which we cannot ask to our users. Desktop notification is correctly delivered embedding into the card the variable text. The question is: why the card is not able to embed an image from an URL?

**Comment by pyrech** [comment]
> I need to re-open, but I don't find the way, as I think issue is not related to my OSX system, which currently gets already desktop notifications, but the limit of this package to show in the desktop also an image. Any way to show also the image?

> The issue is concerned to ALL OSX for sure, and probably also to Windows OS, which didn't apply specific programmic actions, which we cannot ask to our users. Desktop notification is correctly delivered embedding into the card the variable text. The question is: why the card is not able to embed an image from an URL?

Again, this package is a small abstraction around the desktop notifiers available on your system. If those notifiers do not accept an option to embed an image, then there is *nothing* we can do.

By default, on OSX we use an AppleScript (through the executable `osascript`) which do not support setting a custom icon.

I just checked on latest MacOS with `terminal-notifier` (which is supported by jolinotif, just run `brew install terminal-notifier` to install it). And even if `terminal-notifier` provides an `-appIcon` option, it doesn't work. It looks like this is directly related to how MacOS notifications work (see this comment explaining the issue https://github.com/mikaelbr/node-notifier/issues/71#issuecomment-147209781).

The only thing here we can do here is to change a bit the behaviour of `terminal-notifier` to embed an image instead of trying to change the notification's icon by using `-contentImage` instead of `-appIcon`:

<img width="472" alt="screen-1" src="https://user-images.githubusercontent.com/2021641/107752732-71777500-6d1f-11eb-9337-3f725a183311.png">

But again, this will work only if yours users have the `terminal-notifier` available on their computer - which is not the case by default.

**Comment by Echecivuole** [comment]
> rk only if yours users have the `te`



> > I need to re-open, but I don't find the way, as I think issue is not related to my OSX system, which currently gets already desktop notifications, but the limit of this package to show in the desktop also an image. Any way to show also the image?
> 
> > The issue is concerned to ALL OSX for sure, and probably also to Windows OS, which didn't apply specific programmic actions, which we cannot ask to our users. Desktop notification is correctly delivered embedding into the card the variable text. The question is: why the card is not able to embed an image from an URL?
> 
> Again, this package is a small abstraction around the desktop notifiers available on your system. If those notifiers do not accept an option to embed an image, then there is **nothing** we can do.
> 
> By default, on OSX we use an AppleScript (through the executable `osascript`) which do not support setting a custom icon.
> 
> I just checked on latest MacOS with `terminal-notifier` (which is supported by jolinotif, just run `brew install terminal-notifier` to install it). And even if `terminal-notifier` provides an `-appIcon` option, it doesn't work. It looks like this is directly related to how MacOS notifications work (see this comment explaining the issue [mikaelbr/node-notifier#71 (comment)](https://github.com/mikaelbr/node-notifier/issues/71#issuecomment-147209781)).
> 
> The only thing here we can do here is to change a bit the behaviour of `terminal-notifier` to embed an image instead of trying to change the notification's icon by using `-contentImage` instead of `-appIcon`:
> 
> <img alt="screen-1" width="472" src="https://user-images.githubusercontent.com/2021641/107752732-71777500-6d1f-11eb-9337-3f725a183311.png">
> 
> But again, this will work only if yours users have the `terminal-notifier` available on their computer - which is not the case by default.

ok thanks for your reply. Got it this is limitation OSX only. Last question: Is the above issue related also to the "TERMINAL-NOTIFIER" text and icon?

thanks!
