### ISSUE TITLE
Click on notification to open link

### ISSUE THREAD

**Issue by Echecivuole** [jolicode/JoliNotif#74]
Hello, I didn't find a way to get url linked to the desktop notification. How to enable it?

**Comment by lyrixx** [comment]
Is it possible natively ? I mean without this wrapper ?

**Comment by Echecivuole** [comment]
> Is it possible natively ? I mean without this wrapper ?

I don't know, but developer should provide a way as a notification which cannot be link to the URL is not so useful...

**Comment by lyrixx** [comment]
Hello, Unfortunately, if it's not possible natively, this lib could not do it.
If you find a way to make it works, we'll be super happy to add support in JoliNotif.
In the meantime, I'll close this issue since we can not do anything.

Thanks for your proposal 👍🏼
