### ISSUE TITLE
Field for answer

### ISSUE THREAD

**Issue by eleimt** [jolicode/JoliNotif#75]
Hello.
Please tell me. It is possible to work with additional notification functionality. For example a field for an answer?
![image](https://user-images.githubusercontent.com/16452150/108552436-5cdc4380-7302-11eb-9929-a85e62e9f23a.png)

**Comment by pyrech** [comment]
Hello @eleimt 

Indeed, this is currently not supported by JoliNotif.

On Windows 10, JoliNotif uses a notifier named [Toaster](https://github.com/nels-o/toaster) and I am not sure than Toaster proposes these kind of features.

**Comment by eleimt** [comment]
@pyrech
I just readed this article https://docs.microsoft.com/ru-ru/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts?tabs=builder-syntax and think about this

**Comment by lyrixx** [comment]
@eleimt Do you think you can work on a PR?

**Comment by eleimt** [comment]
@lyrixx to do this?

**Comment by lyrixx** [comment]
wep :) To give a try

**Comment by eleimt** [comment]
I do not even know.  I did not delve further into the problem.  Perhaps interesting.
