### ISSUE TITLE
In the docs, Advanced usage is referenced but the page is not found

### ISSUE THREAD

**Issue by newadventure079** [jolicode/JoliNotif#86]
For example, at `https://github.com/jolicode/JoliNotif/blob/main/doc/02-notification.md`, it mentions "Advanced usage" but that page is not found.  `https://github.com/jolicode/JoliNotif/blob/main/doc/04-advanced-usage.md`

The same applies for other pages thru the help docs

**Comment by pyrech** [comment]
Thanks for the issue. It looks like the last documentation refactoring left some incorrect links. If I remember correctly the "advanced usage" documentation was renamed "cron usage".

I will correct them asap unless someone want to do it themself before 🙂
